### ISSUE TITLE
External stylesheet with unique id

### ISSUE THREAD

**Issue by owenvoke** [hill/tldr-chrome#2]
In Chrome extensions, you can specify a stylesheet which I think may be a better way of managing the files. (see [content_scripts])

In [v0.2.0] it mentions to remove inherited styles from the document, it may be worth applying a unique id to the main popup (as you will only have 1 at a time) such as `#tldr-chrome-popup`, and then apply the styles under this.

I've tested this locally and it seems to work fine. It would also mean that the styles wouldn't be applied dynamically as in [main.js#L8] and throughout `main.js`.

[v0.2.0]: https://github.com/hill/tldr-chrome/blob/master/todo.md#v020
[content_scripts]: https://developer.chrome.com/extensions/content_scripts
[main.js#l8]: https://github.com/hill/tldr-chrome/blob/master/main.js#L8

**Comment by hill** [comment]
That's awesome! Did not even know you could use stylesheets. That's a way better system than my `Object.assign` styles littered through `main.js` haha.

I'll implement that later this week (unless you would like to have a go sooner?)

Thanks for your help.

**Comment by owenvoke** [comment]
I might have a look at it 👍

**Comment by owenvoke** [comment]
Started this on a new branch here: [feature/seperate-stylesheet]

I've got the fonts working in 77ab5d6908879a377b7fbdf5eb5357a253a7d7d5, but I'm not entirely sure if they are the right sort of fonts. As far as I know, there isn't a better way to do this for local files. But I personally think the standard `monospace` font looks a bit better.

------------------

This is how it looks with the `OfficeCodePro` fonts.

![OfficeCodePro](https://image.prntscr.com/image/omI_Dj_FQBOnfY72E6MyLA.png)

This is how it looks with the `monospace` fonts.

![monospace](https://image.prntscr.com/image/Buy5x6IXRo_8QqYEXfIrhw.png)

[feature/seperate-stylesheet]: https://github.com/pxgamer/tldr-chrome/tree/feature/seperate-stylesheet

**Comment by owenvoke** [comment]
I have noticed that it inherits a lot of the styling from the page still, so I've come across the CSS [`all`][all] property. This resets all styles to their defaults.

I've been testing and it seems to work fine (see edc14970d2c9a120166d2beda7a001fd3db0ce6a).

There are a couple of other things that would be nice to update, but as they are other features, they should be in seperate branches (such as refactoring the JS to use consistent ES or JS definitions).

[all]: https://developer.mozilla.org/en-US/docs/web/css/all

**Comment by hill** [comment]
I think you might be right with the monospace font over Office Code Pro. I'll go ahead and remove the Office Code files and references. 😄

**Comment by owenvoke** [comment]
@hill, as it's currently using an scss file (which requires transpiling to a css file) it may be worth mentioning this in the README install steps.

At least until a production-ready stylesheet is available.

**Comment by hill** [comment]
Haha literally typing it right now 😉
