### ISSUE TITLE
Ensure tooltip does not disappear when clicking inside the tooltip

### ISSUE THREAD

**Issue by hill** [hill/tldr-chrome#7]
Ensure tooltip does not disappear when clicking inside the tooltip.

It prevents allowing copy/paste of the commands as well as clicking the link in the not found page.

**Comment by owenvoke** [comment]
I found that this can be fixed using:

```js
window.onmousedown = (mouseDownEvent) => {
  let isPopup = false
  mouseDownEvent.path.forEach((elementInPath) => {
    if (elementInPath.id === 'tldr-chrome') isPopup = true
  })

  if (!isPopup) {
    removeTooltip()
  }
}
```
(As per 3042a9858f22c1d3062cacd614c11ce1f2e9c1aa)

But the thing is, this seems like kind of a long-winded way of doing it. I'm sure there's a better option. :+1:

**Comment by hill** [comment]
@pxgamer - that is an option. I'm wondering if this would be more or less resource intensive than creating a div that spans the entire page with a z-index below the popup and using that to detect a click outside the popup? Any ideas?
