### ISSUE TITLE
This app 's tl;dr info is out-of-date from the master repo at https://github.com/tldr-pages/tldr-pages.github.io

### ISSUE THREAD

**Issue by StewAlexander-com** [hill/tldr-chrome#9]
@pxgamer 

This app is out -of-date from the master repo at https://github.com/tldr-pages/tldr/tree/master/pages

Please update your app to include the latest info, or better yet build a curl / wget / git script to pull in the changes to the master repo from time-to-time

Please see tickethttps://github.com/tldr-pages/tldr-pages.github.io/issues/37 for reference

**Comment by owenvoke** [comment]
It's not my app, it belongs to @hill.

Currently this app pulls the page data on the fly from the master branch.

To search for `ss` (a Linux page), on https://tldr.ostera.io you'll need to search for [`linux/ss`](https://tldr.ostera.io/linux/ss).

For this app, it should be able to support non-common platforms in theory, but looks like the code isn't fully implemented. Feel free to create a PR if you'd like. :+1:

**Comment by StewAlexander-com** [comment]
Ah, hmm

@hill - Any chance you can add some language on the main page on how to search specific OS types, it wasn't clear enough to me, and I bet others, or have it search globally and put the OS type in the search results?

@pxgamer thanks for the quick reply +1

**Comment by StewAlexander-com** [comment]
@pxgamer new this whole github thing, so not sure how to create a pull request, 

You could teach me, or if you could it, great otherwise, thanks again for the quick response, hopefully @hill will respond

**Comment by sbrl** [comment]
@StewAlexanderACC: See [this help article on PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) :-)

**Comment by StewAlexander-com** [comment]
Ok will take a look when I get a chance @sbrl thanks

**Comment by hill** [comment]
Hi @StewAlexanderACC - apologies for my late response.

Yes this hasn't been implemented yet. If you'd like to have a crack and update it feel free to submit a PR! 😄 

I will look into updating within the next month if no progress is made (sorry a bit busy at the moment 😬 )

Thanks for making the issue and bringing it up!

**Comment by StewAlexander-com** [comment]
@Hill - where does this stand? Do you need a new owner for this project?

**Comment by StewAlexander-com** [comment]
@hill - Any progress?

**Comment by StewAlexander-com** [comment]
Since nothing in like 6 months closing, @hill would be nice to have this database updated -- if I have some free development cycles later I might assist

**Comment by hill** [comment]
Sorry @StewAlexander-com - I believe @piraces maintains a fork of this repo and extension [here](https://github.com/piraces/tldr-extension-browser).

I'll look into archiving (or transferring?) this repo and pulling my version from the chrome app store as I really don't have time to maintain it.
